UPDATE_INCREASE_EXISTING_ITEM_QUANTITY_BY_CODE = """
update items
set QUANTITY = QUANTITY + ?
WHERE CODE = ?
"""

DECREASE_EXISTING_ITEM_QUANTITY_BY_CODE = """
update items
set QUANTITY = QUANTITY - ?
WHERE CODE = ?
"""

INCREASE_EXISTING_SOLD_ITEM_QUANTITY_BY_CODE = """
update items
set QUANTITY = QUANTITY + ?
WHERE CODE = ?
"""

DECREASE_EXISTING_SOLD_ITEM_QUANTITY_BY_CODE = """
update items
set QUANTITY = QUANTITY - ?
WHERE CODE = ?
"""


UPDATE_CLOSED_STATUS_BY_CODE = """
update receipts
set STATUS = ?
WHERE CODE = ?
"""