CREATE_ITEMS_TABLE = """
CREATE TABLE IF NOT EXISTS items(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
CODE INTEGER NOT NULL,
DESCRIPTION TEXT NOT NULL,
PRICE INTEGER,
QUANTITY DOUBLE DEFAULT 0,
unique (CODE)
)
"""

CREATE_SOLD_ITEMS_TABLE = """
CREATE TABLE IF NOT EXISTS sold_items(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
CODE INTEGER NOT NULL,
DESCRIPTION TEXT NOT NULL,
QUANTITY DOUBLE DEFAULT 0,
PRICE INTEGER,
TIME_SOLD DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(CODE) REFERENCES items(CODE)
)
"""

CREATE_RECEIPTS_TABLE = """
CREATE TABLE IF NOT EXISTS receipts(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
CODE INTEGER NOT NULL,
STATUS INTEGER NOT NULL DEFAULT 0,
TIME_CREATED DATETIME,
unique (CODE)
)
"""

CREATE_RECEIPTS_ITEMS = """
CREATE TABLE IF NOT EXISTS receipts_items(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
RECEIPT_CODE INTEGER NOT NULL,
ITEM_CODE INTEGER NOT NULL,
PRICE DOUBLE,
QUANTITY DOUBLE NOT NULL default 1,
FOREIGN KEY(ITEM_CODE) REFERENCES items(CODE),
FOREIGN KEY(RECEIPT_CODE) REFERENCES receipts(CODE)
)
"""
